set nocp                    " 'compatible' is not set
filetype plugin on          " plugins are enabled

syntax enable               " switch on sytax highlighting

set showcmd                 " show command in status line
set backspace=2             " same as 'eol', 'indent', and 'start'

set tabstop=2               " set <TAB> to equal 2
set shiftwidth=2            " set autoindent to equal 2
set shiftround              " round <TAB> to nearest multiple of 'shiftwidth'
set expandtab               " expand <TAB> and autoindent to spaces
